vaccines:
  - owid_name: "Abdala"
    org_name:
      - "Abdala"
      - "CIGB - CIGB-66"
  - owid_name: "ZF2001"
    org_name:
      - "Anhui ZL - Recombinant"
      - "Anhui ZL - Zifivax"
      - "RBD-Dimer"
      - "ZF2001"
  - owid_name: "IMBCAMS"
    org_name:
      - "IMB - Covidful"
      - "IMB - Inactivated"
  - owid_name: "Oxford/AstraZeneca"
    org_name:
      - "AstraZeneca - AZD1222"
      - "AstraZeneca - Vaxzevria"
      - "SII - Covishield"
  - owid_name: "Sinopharm/Beijing"
    org_name:
      - "Beijing CNBG - BBIBP-CorV"
      - "Beijing CNBG - Inactivated"
      - "Sinopharm/HayatVax"
      - "Julphar - Hayat-Vax"
  - owid_name: "Corbevax"
    org_name: "Biological E - Corbevax"
  - owid_name: "Covaxin"
    org_name: "Bharat - Covaxin"
  - owid_name: "CanSino"
    org_name:
      - "CanSino - Ad5-nCOV"
      - "CanSino - Convidecia"
  - owid_name: "KoviVac/Chumakov"
    org_name: "Chumakov - Covi-Vac"
  - owid_name: "Sputnik V"
    org_name:
      - "Gamaleya - Sputnik V"
      - "Gamaleya - Gam-Covid-Vac"
  - owid_name: "Sputnik Light"
    org_name: "Gamaleya - Sputnik-Light"
  - owid_name: "Johnson&Johnson"
    org_name:
      - "Janssen - Ad26.COV 2.5"
      - "Janssen - Ad26.COV 2-S"
  - owid_name: "KCONVAC"
    org_name: "Shenzhen - LV-SMENP-DC"
  - owid_name: "Moderna"
    org_name:
      - "Moderna - mRNA-1273"
      - "Moderna - Spikevax"
      - "Moderna – Spikevax Bivalent Original/Omicron BA.1"
      - "Moderna – Spikevax Bivalent Original/Omicron  - Generic"
      - "Moderna – Spikevax Bivalent Original/Omicron BA.4/BA.5"
  - owid_name: "Novavax"
    org_name:
      - "Novavax - Covavax"
      - "Novavax-NUVAXOVID"
      - "SII - Covovax"
  - owid_name: "Pfizer/BioNTech"
    org_name:
      - "Pfizer BioNTech - Comirnaty"
      - "Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.1"
      - "Pfizer BioNTech - Comirnaty Bivalent Original/Omicron BA.4/BA.5"
      - "Pfizer BioNTech - Comirnaty Bivalent Original/Omicron - Generic"
  - owid_name: "QazVac"
    org_name:
      - "QazVac"
      - "RIBSP - QazCovid"
      - "RIBSP - QazVac"
  - owid_name: "Sinovac"
    org_name: "Sinovac - CoronaVac"
  - owid_name: "Soberana02"
    org_name:
      - "Soberana02"
      - "Finlay - Soberana Plus"
      - "Finlay - Soberana-02"
  - owid_name: "Valneva"
    org_name:
      - "Valneva - VLA2001"
  - owid_name: "EpiVacCorona"
    org_name: "SRCVB - EpiVacCorona"
  - owid_name: "Sinopharm/Wuhan"
    org_name: "Wuhan CNBG - Inactivated"
  - owid_name: "COVIran Barekat"
    org_name: "Shifa - COVIran Barakat"
  - owid_name: "ZyCoV-D"
    org_name: "Zydus - ZyCov-D"
  - owid_name: "Turkovac"
    org_name: "Turkovac"

countries:
  - org_name: "Afghanistan"
    owid_name: "Afghanistan"
  - org_name: "Albania"
    owid_name: "Albania"
  - org_name: "Algeria"
    owid_name: "Algeria"
  - org_name: "Andorra"
    owid_name: "Andorra"
  - org_name: "Angola"
    owid_name: "Angola"
  # - org_name: "Anguilla"
  #   owid_name: "Anguilla"
  - org_name: "Antigua and Barbuda"
    owid_name: "Antigua and Barbuda"
  - org_name: "Armenia"
    owid_name: "Armenia"
  - org_name: "Australia"
    owid_name: "Australia"
  # - org_name: "Azerbaijan"
  #   owid_name: "Azerbaijan"
  - org_name: "Bahrain"
    owid_name: "Bahrain"
  - org_name: "Barbados"
    owid_name: "Barbados"
  - org_name: "Belarus"
    owid_name: "Belarus"
  # - org_name: "Belize"
  #   owid_name: "Belize"
  - org_name: "Benin"
    owid_name: "Benin"
  - org_name: "Bhutan"
    owid_name: "Bhutan"
  - org_name: "Bonaire Sint Eustatius and Saba"
    owid_name: "Bonaire Sint Eustatius and Saba"
  - org_name: "Bosnia and Herzegovina"
    owid_name: "Bosnia and Herzegovina"
  - org_name: "Botswana"
    owid_name: "Botswana"
  - org_name: "British Virgin Islands"
    owid_name: "British Virgin Islands"
  - org_name: "Brunei Darussalam"
    owid_name: "Brunei"
  - org_name: "Burkina Faso"
    owid_name: "Burkina Faso"
  - org_name: "Burundi"
    owid_name: "Burundi"
  - org_name: "Cabo Verde"
    owid_name: "Cape Verde"
  - org_name: "Cambodia"
    owid_name: "Cambodia"
  - org_name: "Cameroon"
    owid_name: "Cameroon"
  - org_name: "Cayman Islands"
    owid_name: "Cayman Islands"
  - org_name: "Central African Republic"
    owid_name: "Central African Republic"
  - org_name: "Chad"
    owid_name: "Chad"
  - org_name: "Colombia"
    owid_name: "Colombia"
  - org_name: "Comoros"
    owid_name: "Comoros"
  - org_name: "Congo"
    owid_name: "Congo"
  - org_name: "Côte d’Ivoire"
    owid_name: "Cote d'Ivoire"
  - org_name: "Costa Rica"
    owid_name: "Costa Rica"
  - org_name: "Democratic Republic of the Congo"
    owid_name: "Democratic Republic of Congo"
  - org_name: "Djibouti"
    owid_name: "Djibouti"
  - org_name: "Egypt"
    owid_name: "Egypt"
  - org_name: "Equatorial Guinea"
    owid_name: "Equatorial Guinea"
  - org_name: "Eswatini"
    owid_name: "Eswatini"
  - org_name: "Ethiopia"
    owid_name: "Ethiopia"
  - org_name: "Gabon"
    owid_name: "Gabon"
  - org_name: "Gambia"
    owid_name: "Gambia"
  - org_name: "Ghana"
    owid_name: "Ghana"
  # - org_name: "Grenada"
  #   owid_name: "Grenada"
  - org_name: "Guinea"
    owid_name: "Guinea"
  - org_name: "Guinea-Bissau"
    owid_name: "Guinea-Bissau"
  - org_name: "Haiti"
    owid_name: "Haiti"
  - org_name: "Honduras"
    owid_name: "Honduras"
  - org_name: Indonesia
    owid_name: Indonesia
  - org_name: "Iran (Islamic Republic of)"
    owid_name: "Iran"
  - org_name: "Iraq"
    owid_name: "Iraq"
  # - org_name: "Japan"
  #   owid_name: "Japan"
  - org_name: "Jordan"
    owid_name: "Jordan"
  - org_name: "Kenya"
    owid_name: "Kenya"
  - org_name: "Kuwait"
    owid_name: "Kuwait"
  - org_name: "Lebanon"
    owid_name: "Lebanon"
  - org_name: "Lesotho"
    owid_name: "Lesotho"
  - org_name: "Liberia"
    owid_name: "Liberia"
  # - org_name: "Luxembourg"
  #   owid_name: "Luxembourg"
  - org_name: "Libya"
    owid_name: "Libya"
  # - org_name: "Kiribati"
  #   owid_name: "Kiribati"
  # - org_name: "Kosovo"
  #   owid_name: "Kosovo"
  - org_name: "Madagascar"
    owid_name: "Madagascar"
  - org_name: "Malawi"
    owid_name: "Malawi"
  - org_name: "Maldives"
    owid_name: "Maldives"
  - org_name: "Mali"
    owid_name: "Mali"
  - org_name: "Mauritania"
    owid_name: "Mauritania"
  - org_name: "Mauritius"
    owid_name: "Mauritius"
  # - org_name: "Mexico"
  #   owid_name: "Mexico"
  - org_name: "Republic of Moldova"
    owid_name: "Moldova"
  - org_name: "Montserrat"
    owid_name: "Montserrat"
  - org_name: "Morocco"
    owid_name: "Morocco"
  - org_name: "Mozambique"
    owid_name: "Mozambique"
  - org_name: "Myanmar"
    owid_name: "Myanmar"
  - org_name: "Namibia"
    owid_name: "Namibia"
  # - org_name: "Nauru"
  #   owid_name: "Nauru"
  - org_name: "Nepal"
    owid_name: "Nepal"
  - org_name: "Nicaragua"
    owid_name: "Nicaragua"
  - org_name: "Niger"
    owid_name: "Niger"
  - org_name: "Nigeria"
    owid_name: "Nigeria"
  - org_name: "Niue"
    owid_name: "Niue"
  - org_name: "North Macedonia"
    owid_name: "North Macedonia"
  - org_name: "Oman"
    owid_name: "Oman"
  # - org_name: "Papua New Guinea"
  #   owid_name: "Papua New Guinea"
  - org_name: Pakistan
    owid_name: Pakistan
  - org_name: "occupied Palestinian territory"
    owid_name: "Palestine"
  # - org_name: "Portugal"
  #   owid_name: "Portugal"
  - org_name: Philippines
    owid_name: Philippines
  # - org_name: Republic of Korea
  #   owid_name: South Korea
  - org_name: Qatar
    owid_name: Qatar
  - org_name: "Rwanda"
    owid_name: "Rwanda"
  - org_name: "Saint Vincent and the Grenadines"
    owid_name: "Saint Vincent and the Grenadines"
  - org_name: "San Marino"
    owid_name: "San Marino"
  - org_name: "Sao Tome and Principe"
    owid_name: "Sao Tome and Principe"
  - org_name: "Senegal"
    owid_name: "Senegal"
  - org_name: "Seychelles"
    owid_name: "Seychelles"
  - org_name: "Sierra Leone"
    owid_name: "Sierra Leone"
  - org_name: "Sint Maarten"
    owid_name: "Sint Maarten (Dutch part)"
  # - org_name: "Solomon Islands"
  #   owid_name: "Solomon Islands"
  - org_name: "Somalia"
    owid_name: "Somalia"
  - org_name: South Africa
    owid_name: South Africa
  - org_name: "South Sudan"
    owid_name: "South Sudan"
  - org_name: "Sri Lanka"
    owid_name: "Sri Lanka"
  - org_name: "Sudan"
    owid_name: "Sudan"
  # - org_name: "Sweden"
  #   owid_name: "Sweden"
  - org_name: "Syrian Arab Republic"
    owid_name: "Syria"
  - org_name: "United Republic of Tanzania"
    owid_name: "Tanzania"
  - org_name: "Tajikistan"
    owid_name: "Tajikistan"
  - org_name: "Timor-Leste"
    owid_name: "Timor"
  - org_name: "Togo"
    owid_name: "Togo"
  - org_name: "Tunisia"
    owid_name: "Tunisia"
  - org_name: "Turkmenistan"
    owid_name: "Turkmenistan"
  - org_name: "Turks and Caicos Islands"
    owid_name: "Turks and Caicos Islands"
  - org_name: "Tuvalu"
    owid_name: "Tuvalu"
  - org_name: "Uganda"
    owid_name: "Uganda"
  - org_name: "Ukraine"
    owid_name: "Ukraine"
  - org_name: "Uzbekistan"
    owid_name: "Uzbekistan"
  - org_name: "United Arab Emirates"
    owid_name: "United Arab Emirates"
  - org_name: "United Republic of Tanzania"
    owid_name: "Tanzania"
  - org_name: "Venezuela (Bolivarian Republic of)"
    owid_name: "Venezuela"
  - org_name: "Viet Nam"
    owid_name: "Vietnam"
  - org_name: "Yemen"
    owid_name: "Yemen"
  # - org_name: "Zambia"
  #   owid_name: "Zambia"
